### PR TITLE
Refactoring HDPI

### PR DESCRIPTION
**Pull request by Ortner**
This is the proposed solution to #607 

It should actually have the same functionality as before, but it's tested only using a Mac.

It seems, that the glass Robot on Windows uses Real (HDPI) coordinates. That would actually be in conflict with the definition of ` com.sun.glass.ui.Robot.getScreenCapture(int x, int y, int width, int height, boolean isHiDPI)`. Let's see what Travis says.

### CODE REVIEW

**Comment by brcolow** [comment]
If you can get the tests to pass on all 3 platforms, then I will be happy to merge this as it's a much better approach than my hacking. When I was working on this it was somewhat of a nightmare to get all 3 platforms to behave reasonably.

**Comment by Ortner** [comment]
I can see your point :-).

Well, if it's not running on the first try, I'll try to do it right. Might take some buils on the server, as failures are in the environments I don't have access to.

**Comment by Ortner** [comment]
## ScratchPad Run1

### Linux

Travis died, so no logs -> next run

### Windows
Step one: Check BoundLocator(JavaOnly) and Robot Coordinates  
Unscaled Windows runs  

Java1.8 200%:
AwtRobot:
- nullOffset: 
  - JavaBounds OK
  - RobotCoordinates (click) NOK
- clickOffset: click was `1/scale`, so Robot need a factor of `scale`

GlassRobot:
- nullOffset: 
  - JavaBounds OK
  - RobotCoordinates (click) NOK
- clickOffset: click was `scale`, so Robot need a factor of `1/scale` (currently scale is applied, effectively removes this requirement)

Next step: Fix Robots and verify Window translation scaling (`defaultOffsetTest`)

**Comment by Ortner** [comment]
## Intermediate Note

Some of our tests aren't setup correctly (at least for MacOS). This might be the reason for the flakyness of some Tests. 
I had to fix the BaseTest, to clean up properly (as the stages of previous test were hiding my stage). After that, the NodeMatcher didn't run any more. Reason was, the Cleanup in the test before did remove the stage. NodeMatcher did only extend FxRobot adapter and called: FxToolkit.registerPrimaryStage(); + FxToolkit.setupFixture. No stage was created to show the component in.
Also: If you change the coordinates of the Stage (`stage.setX(0);stage.setY(0);`) most of the following tests are translated too. The isolation between the tests is not very good currently.

**Comment by Ortner** [comment]
## ScratchPad Run 2

### Windows

Window offset is OK  
But there is a bug in capturePixelColor for AWTRobot, as CaptureRegion works should be a Bug in pixel retrieval.


### Linux

Running Tests (excerpt)
.4 Glass with scaling Java 8 Running
.7 Java 10 noScale works

Failing Tests:
Build 9+10 are failing both JDK 10 (-Djdk.gtk.version=3?) one uses glass other one awt, so one log should be enough

As far as I can see, those are the only scaled Java10 tests

AwtRobot:
- nullOffset:
  - JavaBounds OK
  - RobotCoordinates (click) NOK
- clickOffset: click was 1/scale, so Robot need a factor of scale

GlassRobot:

- nullOffset:
  - JavaBounds OK
  - RobotCoordinates (click) NOK
- clickOffset: click was scale, so Robot need a factor of 1/scale 

Pretty much same as for windows. Didn't check the Linux builds for contra indication (just too many, with way too much output). Let Travis do the work.

**Comment by brcolow** [comment]
Amazing work. Do you mind squashing to one commit? Thanks @Ortner

**Comment by brcolow** [comment]
I went ahead and squashed it for you in #609 - I don't mean to insert my joint authorship on your work like that, not sure how I can have git not do that. Anyways, if it's okay with you I will merge #609 - if not and you want to squash this one, that's fine too.

**Comment by Ortner** [comment]
@brcolow: Thanks for squashing, that reduces the risk, that I mess up my local branches again :-).
And I guess for your commitment to the project you deserve the co authorship anyway (by the way thanks for that). Especially in this case, you did set-up all the build servers and the first implementation this PR is based on.
So feel free to squash my PRs whenever you want :-).

**Comment by brcolow** [comment]
Thanks very much. Also just to note on command-line git you are listed as the sole author, and I am just the "commiter" - so that's better IMO. Merged in https://github.com/TestFX/TestFX/pull/609

**Pull request closed without merging**
