### PR TITLE
Junit5 adapter

### PR DESCRIPTION
**Pull request by SimY4**
This is a very simple TestFX idiomatic junit5 adapter. It can be used in two ways. Either extending the ApplicationAdapter ( similar to testfx-junit adapter ) or by declaring extension on your test class i.e.:
```
@ExtendsWith(ApplicationExtension.class)
class MyJunit5Test {
    /* after that you can declare methods annotated with @Init */
    @Init
    void sceneInitMethod() { }
    /* or @Start */
    @Start
    void start(Scene scene) { }
    /* or @Stop */
    @Stop
    void stop() {}
    /* to get the access to FxRobot instance during the test, just declare the test parameter of type FxRobot */
    @Test
    void shouldTestFx(FxRobot robot) {
         robot.click("whatever");
    }
}
```

### CODE REVIEW

**Comment by brcolow** [comment]
Wow! Thanks for this. It looks good to me. Let me test it out a bit, I'll get back to you!

**Comment by SimY4** [comment]
@brcolow Field injection is not automatic, but can be very easily controlled by extensions. I can implement FxRobot field injection as well, good point.

**Comment by brcolow** [comment]
@SimY4 Is it appropriate to change the dependencies from `all` to `core` here as you did in the other PR?

**Comment by SimY4** [comment]
@brcolow sure, I forgot to do that here.

**Comment by brcolow** [comment]
Restarted build as JVM crashed on headless macOS build (I submitted a report to Oracle...maybe something will come of it). Will squash-merge when CI is green!

**Comment by SimY4** [comment]
@brcolow Thank you! Can I ask you to make a release of these changes? :) If its not too hard.

**Comment by brcolow** [comment]
Thanks so much for this PR. I will do a release ASAP, just need to figure a couple things out first.

**Pull request merged**
