### PR TITLE
(feat) ListViews provides a row selected matcher.

### PR DESCRIPTION
**Pull request by Ciruman**
The ListViews class did not provide the selected functionality. It could be complexer checking all the parameters provided in a multiselection, but I though that it would be enough for the first version and most cases.
The first commit was not formated, that's why I revert the changes and commit them again. I am quite tired :P

### CODE REVIEW

**Comment by hastebrot** [comment]
Amazing, looks great! Thanks.

**Comment by hastebrot** [comment]
Also note: Somehow your GitHub name is not associated with your commits. This means your contributions will not be listed in `CHANGES.md` which are automatically generated.

I guess this has something to do with the public keys on GitHub and the email address. The GitHub API returns an empty object or null for in `author` field [1].

[1] https://api.github.com/repos/TestFX/TestFX/pulls/202/commits

**Comment by Ciruman** [comment]
Is there anything I can do to change it? I would like to be listed as commiter :-)

**Comment by hastebrot** [comment]
I can manually add you to the `CHANGES.md`. :smiley:

For the next commits you could check the email addresses in https://github.com/settings/ssh and the fields `user.name` and `user.email` that the command `git config --list` lists. You can modify the configuration values with:

~~~
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
~~~

I guess GitHub for Windows or Mac should also let you configure them.

More:
- http://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
- https://help.github.com/articles/generating-ssh-keys/

**Comment by Ciruman** [comment]
Thanks.

**Pull request merged**
