### PR TITLE
Proposed fix for 274: Failing tests in AWTRobotAdapterTest and GlassRobotAdapterTest

### PR DESCRIPTION
**Pull request by Ortner**
## Issue

See #274 
## Solution

Added `waitForFxEvents();` in `FXToolKit`'s `waitForSetup` Method. This should ensure, that all events are processed prior to any tests. The downside is, that tests take a little bit longer (assumed 30-50ms per test).
## Not solved
- Implemented tests --> tests were failing before on my system
- Can anybody (with a similar platform as the build server) implement a testcase with the current master branch, that also fails on the build server because of this condition?

### CODE REVIEW

**Comment by brcolow** [comment]
Are any tests still failing for you on latest master? If so, which ones exactly and what system are they failing on? Thanks.

**Comment by Ortner** [comment]
I'm still running on a Mac (macOS Sierra in the meantime). The tests referenced in #274 are running on the current master now.
The only remaining failing test in my current setup is referenced in #276 (PR #277)

**Comment by Ortner** [comment]
Sorry,
the tests have just not been executed. All of the tests mentioned in #274 are still failing on the current master branch.
I will update the pull request to the current master.

Can you consider to merge #277 too? Failing tests make the seperation of concerns in the pull requests a bit uncomfortable...

**Comment by brcolow** [comment]
I will look into this and #277 as soon as I get OSX builds working on Travis. I am working on this in PR #312 . This will allow us to verify the fixes here and in your other PR. Unfortunately, Travis is [experiencing massive delays on macOS infrastructure](https://www.traviscistatus.com/incidents/nq0sf0srvx8s)

**Comment by brcolow** [comment]
I think I was able to replicate this failure on Travis on macOS:

```
org.testfx.cases.acceptance.FxAssertBasicTest > button_is_not_null FAILED
    java.util.concurrent.TimeoutException
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:432)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
        at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:157)
        at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:277)
        at org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:163)
        at org.testfx.cases.acceptance.FxAssertBasicTest.setup(FxAssertBasicTest.java:47)
```

I am almost done fiddling with the macOS Travis CI infrastructure, but just wanted to make a note for future reference as to the ability to replicate the failure.

**Comment by Ortner** [comment]
I don't think, that this is the right one. I assume this indicates that the GUI is not up and running (this is the first GUI Test executed). I assume the TimeoutException is thrown because the Application Thread is not started, but the application tries to wait for it to initialize. See also merged PR #288, another TimeoutException should be thrown when the test ends.

@brcolow Do you have a link to the Travis output/job?

On the master you should see these tests (only these) failing:
#274 (PR #275):
```
org.testfx.service.adapter.impl.AwtRobotAdapterTest > getCaptureRegion FAILED
    java.lang.AssertionError at AwtRobotAdapterTest.java:274

org.testfx.service.adapter.impl.AwtRobotAdapterTest > getCapturePixelColor FAILED
    java.lang.AssertionError at AwtRobotAdapterTest.java:262

org.testfx.service.adapter.impl.GlassRobotAdapterTest > getCaptureRegion FAILED
    java.lang.AssertionError at GlassRobotAdapterTest.java:273

org.testfx.service.adapter.impl.GlassRobotAdapterTest > getCapturePixelColor FAILED
    java.lang.AssertionError at GlassRobotAdapterTest.java:261
```
#276 (PR#277):
```
org.loadui.testfx.TextInputControlsTest > shouldClearText FAILED
    java.lang.AssertionError at TextInputControlsTest.java:47
        Caused by: java.lang.AssertionError at TextInputControlsTest.java:47
```

**Comment by brcolow** [comment]
So I cherry-picked your work here and put it on the tip of my branch that gets macOS builds running on Travis. You can see that here: https://github.com/TestFX/TestFX/pull/312

However, it seems the 4 failures you noted above are still present: https://travis-ci.org/TestFX/TestFX/jobs/181039353#L1791

**Comment by Ortner** [comment]
Intresting, on my system everything just works well. I'm gonna have a look at that.

**Comment by Ortner** [comment]
## Problem description ##

The problem I figured out is, that the application is not ready when we try to read out the color of the pixels. So we need to wait for the FX-Events to be fully processed after we setup the stage.

The `stage.show()` command is still in the Future of the `setupStage()` command, that calls `waitForSetup` in the end. That's where we are waiting for the events to be processed. So this should be the right place for waiting.

## Possible reasons ##

### WaitForFxEvents() not finished ###
It is possible, that `waitForFxEvents()` is not sucessfull. It calls `waitForFxEvents(int)` which only waits the defined number of loops.

### Rendering not finished ###
As far as I know, the rendering of the nodes runs on the Prism render thread. It might be possible, that the rendering is not done yet, when we fetch the color.

## Tracking down ##
I checked in a version to test the first solution and to further track down the issue. As everything runs on my sytem, can you try on the build server?
I did increase the number of loops that will be waited for the FX-Thread to finish. If it does not work, can you uncomment the sleep in `waitForSetup()` to check if that works. If not the one in `GlassRobotAdapterTest`.

**Comment by Ortner** [comment]
Why are the checks failing?

**Comment by brcolow** [comment]
I increased the semaphore loop count to 100 in my macOS PR. The errors are still present, unfortunately. Also, I think the checks in this PR are failing because of merge conflicts.

**Comment by brcolow** [comment]
Unfortunately adding the sleep does not make it work (and of course makes the tests take an unbearably long time to complete).

**Comment by brcolow** [comment]
You may not be seeing the failing tests because Travis is running with `-Dprism.order=sw` because without it, the JVM crashes as its a headless virtual machine.

**Comment by sstangle73** [comment]
@brcolow just an FYI, I have seen tests pass when running headless and then fail with GUIs and vice versa.

**Comment by brcolow** [comment]
@sstangle73 Yeah, there are clearly some kinks to work out.

**Comment by brcolow** [comment]
I found some information related to this here: 

http://stackoverflow.com/questions/29653934/are-there-known-incompatibilities-that-prevent-javafx-from-running-in-a-virtuali

We have to run in software mode to prevent a JVM crash (which I read was fixed in 8u122, the crash at least), but in doing so certain features won't work.

**Comment by Ortner** [comment]
Well at least we do know now, that this is not a timing issue anymore (1 second is more than enough). I'm gonna try to reproduce it on my system. Unfortunately this is going to happen in the end of the week.

**Comment by brcolow** [comment]
Merged as part of https://github.com/TestFX/TestFX/pull/351 Thanks!

**Pull request closed without merging**
