### PR TITLE
Doc api package

### PR DESCRIPTION
**Pull request by JordanMartinez**
WIP

### CODE REVIEW

**Comment by JordanMartinez** [comment]
The only object left to document in this PR is the `FxAssert` class. However, it is annotated with `@Unstable` because "method signatures need fine-tuning." I feel like that should be resolved before writing any documentation. Otherwise, the first draft of documentation may become outdated once these method signatures are refined.

**Comment by brcolow** [comment]
Sounds good to me. Does that mean this is ready?

**Comment by JordanMartinez** [comment]
yeah. It's ready.

**Comment by JordanMartinez** [comment]
actually, let me fix that previous commit message...

**Comment by JordanMartinez** [comment]
Ok. Now it's ready once tests pass.

**Comment by brcolow** [comment]
Thanks!

**Pull request merged**
