### PR TITLE
Switch usages of Guava types to their corresponding JDK8 types

### PR DESCRIPTION
**Pull request by aalmiray**
TestFX `4.0.4-alpha` makes use of Guavas' `Optional`, `Predicate`, and `Function` as it had binary compatibility with JDK7. However the build was also configured to target Java8 as minimum version.
This PR replaces all usages of Guava's types for their corresponding JDK8 types.

The Gradle build was update slightly too.

### CODE REVIEW

**Comment by aalmiray** [comment]
Relates to #217

**Comment by hastebrot** [comment]
I see, in this changeset are

- a migration from Guava classes to Java 8 classes,
- an update of the Gradle wrapper to 3.0,
- some changes to the import layout.

**Comment by aalmiray** [comment]
Rebased latest master at f26f72e

**Comment by brcolow** [comment]
Would you mind moving the Gradle stuff to a separate PR? Also, I have just merged some commits that re-enable Checkstyle and remove all existing lint errors. If you could rebase (again, sorry) that would be appreciated. I know this is quite annoying, but it will help tremendously going forward as it will increase the confidence I have to merge PRs.

**Comment by aalmiray** [comment]
Will resubmit as 2 separate PRs.

**Comment by aalmiray** [comment]
Closing due to #318

**Pull request closed without merging**
