### PR TITLE
Proposed fix for 276: Failing test in org.loadui.testfx.TextInputControlsTest

### PR DESCRIPTION
**Pull request by Ortner**
## Issue

See #276 
## Implemented Solution

Using clearTextInputControl(testInputControl) instead of ctrl+A, del as this doesn't work on a mac.
## Comments

Now all test are running (even on a Mac :-) ).

I accidentially added some gradle files in one of the commits. I reverted one of them, but I would also favour the insertion of the eclipse plugin. But it is not really in the focus of this issue...

### CODE REVIEW

**Comment by Ortner** [comment]
This commit seems to brak the headless build. Haven't tried the headless option on may system at the moment. I will try to check this.

**Comment by Ortner** [comment]
Updated to current master.
Headless build seems to work now.

**Comment by brcolow** [comment]
What are your thoughts about detecting the OS, and using either Ctrl-A or Command-A instead of calling the clearTextIn method directly?

**Comment by Ortner** [comment]
I think that should work as well. Is it also implemented in the legacy version of TestFX? 

We had the discussion in #276. I personally prefer clearing the text directly.

**Comment by brcolow** [comment]
The change to use `Shortcut`-A was [merged](https://github.com/TestFX/TestFX/pull/333) - so this PR now only adds the documentation - once it is rebased I will merge.

**Comment by brcolow** [comment]
Done in: https://github.com/TestFX/TestFX/pull/335

**Pull request closed without merging**
