### PR TITLE
(refactor) Replace calls to FXRobot with Event.fireEvent.

### PR DESCRIPTION
**Pull request by brcolow**
Ref #228

### CODE REVIEW

**Comment by brcolow** [comment]
It is really quite interesting. There are currently two failing tests:

`keyPressTypeRelease_korean_text` and `keyPressTypeRelease_english_text`.

For some reason the text area text contains everything but the first line (and apparently the first tab character). I am really not sure what would cause this. I tried replacing the Guava `Lists.charactersOf` usage with a Java 8 lambda but got the exact same result.

**Comment by hastebrot** [comment]
Review notes. Need to check:

- [ ] signature of `KeyEvent.KEY_RELEASED, key, ""`
- [ ] signature of `KeyEvent.KEY_TYPED, key, character`
- [ ] signature of `KeyEvent.KEY_PRESSED, key, ""`

**Comment by brcolow** [comment]
If the tabs are removed from the text like so:

```java
String text = "All in the golden afternoon\n" +
        "Full leisurely we glide;\n" +
        "For both our oars, with little skill,\n" +
        "By little arms are plied;\n" +
        "While little hands make vain pretence\n" +
        "Our wanderings to guide.";
``` 

then the text-area contains *no* text at all.

If a tab character is added at the beginning (so that the tab character is the first character of the text) like so:

```java
String text = "\tAll in the golden afternoon\n" +
        "\tFull leisurely we glide;\n" +
        "For both our oars, with little skill,\n" +
        "\tBy little arms are plied;\n" +
        "While little hands make vain pretence\n" +
        "\tOur wanderings to guide.";
``` 

then all the text is there except the initial tab character.

If a tab character is pressed, typed, and released first then the assertion passes:

```java
keyPressTypeRelease(KeyCode.TAB, String.valueOf('\t'));
String text = "All in the golden afternoon\n" +
        "\tFull leisurely we glide;\n" +
        "For both our oars, with little skill,\n" +
        "\tBy little arms are plied;\n" +
        "While little hands make vain pretence\n" +
        "\tOur wanderings to guide.";

// when:
typeText(text);
```

I am very confused.

**Comment by brcolow** [comment]
There is a system property that FXRobot uses to set that it should print debugging hints, `fxrobot.verbose`. Setting it to `true` allows us to see the events injected into the event thread by FXRobot. Unfortunately there is actually a bug and key events are printed incorrectly:

```java
PlatformImpl.runLater(() -> {
    out("doKeyEvent: injecting: {e}");
    FXRobotHelper.sceneAccessor.processKeyEvent(target, e);
});
```

This just prints:

```java
 [FXRobot] doKeyEvent: injecting: {e}
```

Maybe template Strings like that were a planned feature? Who knows. Anyways, at least we can see the mouse events. I added some debugging statements to the new code that mimic the ones from `BaseFXRobot` and as far as I can tell the mouse events are identical:

Old code:
```
org.testfx.service.adapter.impl.JavafxRobotAdapterTest > keyPressTypeRelease_english_text STANDARD_OUT
    [FXRobot] doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1284085598@33ed318d, target = javafx.event.Event$$Lambda$79/1284085598@33ed318d, eventType = MOUSE_MOVED, consumed = false, x = 150.0, y = 213.0, z = 0.0, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
    [FXRobot] doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1284085598@33ed318d, target = javafx.event.Event$$Lambda$79/1284085598@33ed318d, eventType = MOUSE_PRESSED, consumed = false, x = 150.0, y = 213.0, z = 0.0, button = PRIMARY, primaryButtonDown, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
    [FXRobot] doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1284085598@33ed318d, target = javafx.event.Event$$Lambda$79/1284085598@33ed318d, eventType = MOUSE_RELEASED, consumed = false, x = 150.0, y = 213.0, z = 0.0, button = PRIMARY, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
    [FXRobot] doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1284085598@33ed318d, target = javafx.event.Event$$Lambda$79/1284085598@33ed318d, eventType = MOUSE_CLICKED, consumed = false, x = 150.0, y = 213.0, z = 0.0, button = PRIMARY, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
```
New code:
```
    doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, target = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, eventType = MOUSE_MOVED, consumed = false, x = 150.0, y = 213.0, z = 0.0, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
    doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, target = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, eventType = MOUSE_PRESSED, consumed = false, x = 150.0, y = 213.0, z = 0.0, button = PRIMARY, primaryButtonDown, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
    doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, target = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, eventType = MOUSE_RELEASED, consumed = false, x = 150.0, y = 213.0, z = 0.0, button = PRIMARY, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
    doMouseEvent: injecting: MouseEvent [source = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, target = javafx.event.Event$$Lambda$79/1456862715@10bfbd43, eventType = MOUSE_CLICKED, consumed = false, x = 150.0, y = 213.0, z = 0.0, button = PRIMARY, pickResult = PickResult [node = null, point = Point3D [x = 150.0, y = 213.0, z = 0.0], distance = 1.0]
```

I forgot to add `[FXRobot]` to the beginning of the print statement so it doesn't line up *exactly*, but all the numbers appear to be identical.

However what is different is that after the mouse events are run, the old code has the `TextArea` focused and the new code incorrectly has the `TextField` focused.

**Comment by brcolow** [comment]
I am assuming that the `Platform.runLater` calls should be replaced with `asyncFx` calls?

**Comment by brcolow** [comment]
I still am puzzled by this one difference...but I think it's safe to merge this because the input/outputs are identical...and I don't want to hold up Java 9 support any longer. If this becomes a nightmare of people getting failed tests, I will revert the respective changes.

**Pull request merged**
