### PR TITLE
(enhancement) Add module-info.java to testfx-core.

### PR DESCRIPTION
**Pull request by brcolow**
This is an attempt to begin the process of jigsaw modularization for
Java 9. Currently we are not taking advantage of modules for the
different parts of testfx-core, we are simply making everything one big
module but it's the first step.

hamcrest-core and hamcrest-library were used in the compileTestJava
phase of the build and these two artifacts have a split package (both
use the same org.hamcrest package). Instead of messing about with
--patch-modules and the like we replaced all usages of hamcrest-library
with hamcrest-core CoreMatchers where possible. The only place where
this was not feasible was the "closeTo" matcher, which we copied into
CaptureSupportImplTest wholesale. If it turns out we need this Matcher
across the tests we will use a different method of "fixing" this.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
> lol

Just thought I'd share that your commit message made me laugh :laughing:

**Comment by brcolow** [comment]
Context: "lol" and it's successors were rebased away. Probably will be replaced by "lmao", "rofl", "i quit" before long but all will be rebased away to one commit where it appears I am a UNIX master.

**Comment by JordanMartinez** [comment]
I like the "I quit" one :smile:

**Comment by JordanMartinez** [comment]
Maybe you need to call it a day, take a step back for a bit, and the solution will come to you tomorrow?

**Pull request merged**
